### ISSUE TITLE
"aws-iam-authenticator": executable file not found in $PATH

### ISSUE THREAD

**Issue by TediPapajorgji** [ConsenSys/k8s-gh-action#5]
Having an issue come up when using this acton:

```
unable to recognize "kubernetes/apps.yaml": Get https://****.***.****.eks.amazonaws.com/api?timeout=32s: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
```

My actions file:
```
name: Build & Deploy to Kubernetes Cluster

# Manually execute this job now for testing purposes
on: [workflow_dispatch]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish & Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Resembletron
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag,push image to Amazon ECR, and update deployment file
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: resembletron-web
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f docker/Dockerfile.web -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        sed -i '/'$ECR_REGISTRY'\/'$ECR_REPOSITORY'/c\        image: '$ECR_REGISTRY'\/'$ECR_REPOSITORY':'$IMAGE_TAG'' kubernetes/apps.yaml

    - name: Deploy To Resemble Kubernetes Cluster
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f kubernetes/apps.yaml

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
```
